[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "project6"
version = "1.0"
description = "desc6"

[project.entry-points."cogent3_plugins.text"]
myplugin = "project6.my_plugin6:myfunc6"